---
abstract: 'A component that provides non-blocking DNSBL lookups'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  Data::Dumper: 0.47
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-Client-DNSBL
no_index:
  directory:
    - inc
    - t
    - examples
requires:
  Net::IP: 0
  POE: 0.38
  POE::Component::Client::DNS: 1
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.10
